language: node_js
node_js:
  - 'stable'

install:
  - npm install

# https://docs.travis-ci.com/user/build-matrix/

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run build
  - npm start

notifications:
  email: false
