language: node_js
node_js: 10.15
cache:
  yarn: true
addons:
  apt:
    packages:
      - libgconf-2-4
install:
  - yarn install
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

deploy:
  provider: heroku
  api_key:
    secure: f1sN6czDEcFMoypgO27eDYe6TKB4EslPoTLQKvT9/VJwXZLq603IwWF1VMPM+crpHW/FNzGs5kmKarj3CIBDn1r7xdruFqphok7ohJVrb2sjINvvMeymMjCxSPY68CqUv1535xIFCXNQ4DMF9fH6bOvcNo011WaUZOm5bWSkh4zmGcvs55tAUgbdGvXvbwNNzBq4nIPlW9nNa4BujgozBnGx7KrG5n58PLNfqusl+fkRN4uuJ0EzJ5dnJ0YDFZTUbS3pCjQWa7M5h5Ri6+84kqekV4pgaNed2s+spUJoLDn//zD4dwJ0cghCe08MjtmbjuZJDKyyzpXDCRhmt3blqZUHiDwf1cXkDD/qwgHgMBODUApJ25wWvJhhInGROo+4TxPMdLMn1C6oar0cSdFmV/pYbvF11ZjhiiS5fbNcJrUSCvncdxvuSQgSZjAYhIUtwpX/dF1qvcWZK5jKn9+pOdKtYGcfqPPAWqGDaTWoKmyV8UF7lEXbIotme/9WfqmjuIBjSk+byO7k5xG2+6T0YAiJVeIn2xfBtkOmttOo6eTn5UDw7yAj5FypmhfXi6SVtlBG+A18diuhWyGq6A2bSp10NhklKb+ecGN2n1yXv7jXA4W44OmMHBAaO8XyyBvR/8kJb/9CUgsCf01Gr8OwtWmOxfzqQ4mypYykkCULzZ0=
  app:
    master: portfolio1001
    production: portfolio1002
